version: "3.7"
services:
  api:
    container_name: myapp-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        buildno: 1
    image: ymassamar/myapp-api
    ports:
      - "3000:3000"
    volumes:
      - '.:/app'
      - /app/node_modules
    env_file:
      - .env.development
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
