/**
 * @module ldapStrategy
 * @requires passport
 * @requires fs
 */
import passport from 'passport'
import LdapStrategy from 'passport-ldapauth'
import { LDAP_URL, LDAP_BASE, PATH_TO_TLS_LDAP_PUBLIC_KEY, LDAP_SEARCH_FILTER } from '../../../config'
import fs from 'fs'

/**
 * Configure passport for a jwt token strategy that wil return the authenticated user or false if not authenticated
 * @throws error (exemples : parameters missing or invalid, error with passport.use)
 */
export function setupLdapTokenStrategy () {
  const ldapOptions = {
    server: {
      url: LDAP_URL,
      searchBase: LDAP_BASE,
      searchFilter: LDAP_SEARCH_FILTER,
      searchAttributes: ['displayName', 'mail', 'givenName', 'uidNumber', 'uid'],
      tlsOptions: {
        ca: [ fs.readFileSync(PATH_TO_TLS_LDAP_PUBLIC_KEY) ],
      },
    },
  }
  const ldapTokenStrategyCallback = (userLdap, done) => {
    done(null, { userLdap })
  }
  passport.use(new LdapStrategy(ldapOptions, ldapTokenStrategyCallback))
}

/**
 * Return data and info of authentication with passport and ldap
 * @param { Object } req 
 * @param { Object } res
 * @return { Promise } Promise object represents an error thrown or an object with data object and info object generated by passport
 */
export function authenticateLdapPromise (req, res) {
  return new Promise((resolve, reject) => {
    passport.authenticate('ldapauth', { session: false }, (err, data, info) => {
      err ? reject(err) : console.log({ data, info })
      resolve({ data, info })
    })(req, res, (err) => {
      throw err
    })
  })
}
